version: '2'
# storage engines for the microservices of the conference sentiment analysis (csa) application
services:
  datasync_server:
    container_name: datasync_example_server
    image: postgres:latest
    ports:
     - "15432/tcp:5432/tcp"
    environment:
      POSTGRES_USER: qtdatasync
      POSTGRES_PASSWORD: baum42
      POSTGRES_DB: QtDataSync
    volumes:
      - datasync_example_server_data:/var/lib/datasync_example_server/data
  datasync_pgAdmin:
    container_name: datasync_example_pgAdmin
    image: thajeztah/pgadmin4:latest
    ports:
     - "5050/tcp:5050/tcp"
    volumes:
      - datasync_example_pgAdmin_data:/var/lib/datasync_example_pgAdmin/data
volumes:
  datasync_example_server_data:
  datasync_example_pgAdmin_data:
